using System.IO.Compression;
using System.Text;
using Ows.Core.Packaging;

namespace Ows.Core.Verification.Helpers;

/// <summary>
///     Finds explicit authorship or generation markers in packaged text artifacts.
/// </summary>
internal static class ArtifactAuthorshipAnalyzer {
    /// <summary>
    ///     The largest text artifact inspected by the explicit-marker check.
    /// </summary>
    private const long MaximumInspectedBytes = 2_000_000;

    /// <summary>
    ///     Phrases that explicitly identify an AI or code-generation source.
    /// </summary>
    private static readonly string[] ExplicitMarkers = [
        "generated by chatgpt",
        "generated by openai",
        "generated by claude",
        "generated by github copilot",
        "generated with copilot",
        "written by chatgpt",
        "written by claude",
        "llm-generated",
        "ai-generated",
        "as an ai language model"
    ];

    /// <summary>
    ///     Text extensions eligible for explicit-marker inspection.
    /// </summary>
    private static readonly string[] TextExtensions = [
        ".c", ".cc", ".cpp", ".cs", ".css", ".fs", ".fsx", ".go", ".h", ".hpp", ".html", ".java", ".js",
        ".json", ".jsx", ".kt", ".kts", ".md", ".php", ".ps1", ".py", ".rb", ".rs", ".scss", ".sh", ".sql",
        ".swift", ".ts", ".tsx", ".txt", ".vb", ".xml", ".yaml", ".yml"
    ];

    /// <summary>
    ///     Scans eligible packaged artifacts for explicit AI or code-generation markers.
    /// </summary>
    /// <param name="archive">The package archive.</param>
    /// <param name="manifest">The package manifest containing declared artifact paths.</param>
    /// <returns>At most one non-authoritative authorship review finding.</returns>
    public static IReadOnlyList<VerificationFinding> Analyze(ZipArchive archive, OwsManifest manifest) {
        ArgumentNullException.ThrowIfNull(archive);
        ArgumentNullException.ThrowIfNull(manifest);

        var matches = new List<string>();
        foreach (var artifactPath in manifest.ArtifactHashes.Keys) {
            if (!IsTextArtifact(artifactPath)) {
                continue;
            }

            var entry = archive.GetEntry(artifactPath);
            if (entry is null || entry.Length > MaximumInspectedBytes) {
                continue;
            }

            var content = ReadText(entry);
            if (content is null) {
                continue;
            }

            var markers = ExplicitMarkers.Where(marker => content.Contains(marker, StringComparison.OrdinalIgnoreCase))
                                          .ToArray();
            if (markers.Length > 0) {
                var relativePath = artifactPath.StartsWith("artifacts/", StringComparison.Ordinal)
                    ? artifactPath[9..]
                    : artifactPath;
                matches.Add($"{relativePath} ({string.Join(", ", markers)})");
            }
        }

        if (matches.Count == 0) {
            return [];
        }

        return [
            new VerificationFinding {
                Code = "authorship.explicit_marker",
                Severity = "Low",
                Title = "Explicit authorship marker",
                Detail = $"Explicit generation or AI-authorship marker found in {matches.Count} text artifact(s).",
                TechnicalDetail = string.Join("; ", matches),
                ReviewerAction =
                    "Review the marked artifact and its provenance. An explicit marker is not proof of misconduct or AI use."
            }
        ];
    }

    /// <summary>
    ///     Determines whether a package path has a supported text extension.
    /// </summary>
    /// <param name="artifactPath">The package-relative artifact path.</param>
    /// <returns><see langword="true" /> when the artifact is eligible for text inspection.</returns>
    private static bool IsTextArtifact(string artifactPath) {
        var extension = Path.GetExtension(artifactPath);
        return TextExtensions.Contains(extension, StringComparer.OrdinalIgnoreCase);
    }

    /// <summary>
    ///     Reads a small text entry while rejecting binary content.
    /// </summary>
    /// <param name="entry">The archive entry to read.</param>
    /// <returns>The UTF-8 text, or <see langword="null" /> for binary or unreadable content.</returns>
    private static string? ReadText(ZipArchiveEntry entry) {
        using var stream = entry.Open();
        using var memory = new MemoryStream();
        stream.CopyTo(memory);
        var bytes = memory.ToArray();
        if (bytes.Contains((byte) 0)) {
            return null;
        }

        return Encoding.UTF8.GetString(bytes);
    }
}
