apiVersion: 1

datasources:
  - name: OWS Prometheus
    uid: PBFA97CFB590B2093
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: OWS Loki
    uid: PEB814A6C5A1A2E0D
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
